version: '3'
services:
  app:
    build: ./
    container_name: go-rest-api-sample
    working_dir: /go/src/github.com/fiahfy/go-rest-api-sample
    volumes:
      - ./:/go/src/github.com/fiahfy/go-rest-api-sample
    ports:
      - "8080:8080"
    # environment:
    #     GO111MODULE: "on"
